# Generated by Django 3.1 on 2020-08-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200822_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_winner',
        ),
    ]
